#!/bin/bash
# Esto hace una lista con elementos especificos de una extensión

# activar el contenedor de prokka
docker run staphb/prokka:latest prokka

# Pedimos al usuario que ingrese el género de los organismos que va a anotar
#echo "Introduce el genero del organismo analizado: "
#read genero
#echo "El genero es: " $genero

# Esto hace una lista con elementos especificos de una extensión
# Se alimenta de archivos en formato fasta
echo "Haciendo lista de genomas "
ls *nts.fasta >> lista_genomas.txt
# Si tienes *.nts.fasta de corrección de formato generado por anvio.
# Corrección disponible en https://anvio.org/help/main/programs/anvi-script-reformat-fasta/
# anvi-script-reformat-fasta Halomonas_salina_VN10_sedA.fasta -o Halomonas_salina_VN10_sedA.nts.fasta --min-len 1000 --seq-type NT --simplify-names --report-file Hsalina-report.txt
# Esto es útil cuando Prokka tiene errores por nombres en los contigs
#ls *nts.fasta >> lista_genomas.txt

# Usamos un bucle while. Toma los las lineas de la lista generada en y da la orden.
# Entre comillas la orden solo toma el nombre y se lo pega a algo, funciona bien para nombrar archivos generados.
# Sin comillas queda como input directamente para el comando.
cat lista_genomas.txt | while read line;do
    echo "procesando " $line
    docker run staphb/prokka:latest prokka --outdir $genero --prefix "$line" --force --cpus 45 "$line"
    docker run --rm --cpus 15 -v /home/user/Descargas/Secuencias/abi_pseudomonas/ensamble_hibrido:/data staphb/prokka:latest prokka /data/assembly.fasta --outdir /data/docker_prokka --prefix pseudomonas --force --cpus 15
    echo "Listo, ya quedó anotado " $line
done

echo "Se anotaron todos sus genomas. No vuelva pronto"

# Borrar la lista de genomas
rm lista_genomas.txt

# Generar una lista que cuenta los CDS presentes en cada muestra leyendo el gbk generado
grep -c "CDS             " ./$genero/*.gbk > ./$genero/CDS.txt
